-- Optional: Run this in Supabase SQL Editor to seed sample fixtures
-- Or use: supabase db push (for migrations) then run this seed

INSERT INTO fixtures (home_team, away_team, competition, competition_short, kickoff, date, venue, status, home_score, away_score) VALUES
('Arsenal', 'Everton', 'Premier League', 'EPL', '20:30', '2026-03-14', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Brentford', 'Wolves', 'Premier League', 'EPL', '20:30', '2026-03-16', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Bournemouth', 'Manchester United', 'Premier League', 'EPL', '20:30', '2026-03-20', 'Vitality Stadium', 'scheduled', NULL, NULL),
('Brighton & Hove Albion', 'Liverpool', 'Premier League', 'EPL', '14:30', '2026-03-21', 'American Express Stadium', 'scheduled', NULL, NULL),
('Fulham', 'Burnley', 'Premier League', 'EPL', '17:00', '2026-03-21', 'Craven Cottage', 'scheduled', NULL, NULL),
('Everton', 'Chelsea', 'Premier League', 'EPL', '15:00', '2026-03-21', 'Goodison Park', 'scheduled', NULL, NULL),
('Leeds United', 'Brentford', 'Premier League', 'EPL', '20:30', '2026-03-21', 'Elland Road', 'scheduled', NULL, NULL),
('Newcastle United', 'Sunderland', 'Premier League', 'EPL', '13:30', '2026-03-22', 'St James’ Park', 'scheduled', NULL, NULL),
('Aston Villa', 'West Ham United', 'Premier League', 'EPL', '15:45', '2026-03-22', 'Villa Park', 'scheduled', NULL, NULL),
('Arsenal', 'AFC Bournemouth', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Brentford', 'Everton', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Burnley', 'Brighton & Hove Albion', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Turf Moor', 'scheduled', NULL, NULL),
('Crystal Palace', 'Newcastle United', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Selhurst Park', 'scheduled', NULL, NULL),
('Chelsea', 'Manchester City', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Stamford Bridge', 'scheduled', NULL, NULL),
('Liverpool', 'Fulham', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Anfield', 'scheduled', NULL, NULL),
('Manchester United', 'Leeds United', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Old Trafford', 'scheduled', NULL, NULL),
('Nottingham Forest', 'Aston Villa', 'Premier League', 'EPL', '14:30', '2026-04-11', 'The City Ground', 'scheduled', NULL, NULL),
('Sunderland', 'Tottenham Hotspur', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Stadium of Light', 'scheduled', NULL, NULL),
('West Ham United', 'Wolverhampton Wanderers', 'Premier League', 'EPL', '14:30', '2026-04-11', 'London Stadium', 'scheduled', NULL, NULL),
('A.F.C. Bournemouth', 'Manchester City', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Vitality Stadium', 'scheduled', NULL, NULL),
('Arsenal', 'Burnley', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Aston Villa', 'Liverpool', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Villa Park', 'scheduled', NULL, NULL),
('Brentford', 'Crystal Palace', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Chelsea', 'Tottenham Hotspur', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Stamford Bridge', 'scheduled', NULL, NULL),
('Everton', 'Sunderland', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Goodison Park', 'scheduled', NULL, NULL),
('Leeds United', 'Brighton & Hove Albion', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Elland Road', 'scheduled', NULL, NULL),
('Manchester United', 'Nottingham Forest', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Old Trafford', 'scheduled', NULL, NULL),
('Newcastle United', 'West Ham United', 'Premier League', 'EPL', '15:30', '2026-05-17', 'St James’ Park', 'scheduled', NULL, NULL),
('Wolverhampton Wanderers', 'Fulham', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Molineux', 'scheduled', NULL, NULL),
('Brighton & Hove Albion', 'Manchester United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'American Express Stadium', 'scheduled', NULL, NULL),
('Burnley', 'Wolverhampton Wanderers', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Turf Moor', 'scheduled', NULL, NULL),
('Crystal Palace', 'Arsenal', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Selhurst Park', 'scheduled', NULL, NULL),
('Fulham', 'Newcastle United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Craven Cottage', 'scheduled', NULL, NULL),
('Liverpool', 'Brentford', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Anfield', 'scheduled', NULL, NULL),
('Manchester City', 'Aston Villa', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Etihad Stadium', 'scheduled', NULL, NULL),
('Nottingham Forest', 'A.F.C. Bournemouth', 'Premier League', 'EPL', '16:00', '2026-05-24', 'The City Ground', 'scheduled', NULL, NULL),
('Sunderland', 'Chelsea', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Stadium of Light', 'scheduled', NULL, NULL),
('Tottenham Hotspur', 'Everton', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Tottenham Hotspur Stadium', 'scheduled', NULL, NULL),
('West Ham United', 'Leeds United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'London Stadium', 'scheduled', NULL, NULL),
