-- Run this entire file in Supabase SQL Editor to create table + seed data
-- Dashboard: https://supabase.com/dashboard → your project → SQL Editor → New query

-- 1. Create fixtures table
CREATE TABLE IF NOT EXISTS fixtures (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  competition TEXT NOT NULL,
  competition_short TEXT NOT NULL,
  kickoff TEXT NOT NULL,
  date DATE NOT NULL,
  venue TEXT,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'live', 'finished')),
  home_score INTEGER,
  away_score INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fixtures_date ON fixtures(date);
CREATE INDEX IF NOT EXISTS idx_fixtures_date_kickoff ON fixtures(date, kickoff);

ALTER TABLE fixtures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read" ON fixtures;
CREATE POLICY "Allow public read" ON fixtures FOR SELECT USING (true);

-- 2. Clear existing seed data (optional - remove if you want to keep existing)
TRUNCATE fixtures RESTART IDENTITY;

-- 3. Seed dummy fixtures (2 weeks around today)
INSERT INTO fixtures (home_team, away_team, competition, competition_short, kickoff, date, venue, status, home_score, away_score) VALUES
('Arsenal', 'Everton', 'Premier League', 'EPL', '20:30', '2026-03-14', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Brentford', 'Wolves', 'Premier League', 'EPL', '20:30', '2026-03-16', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Bournemouth', 'Manchester United', 'Premier League', 'EPL', '20:30', '2026-03-20', 'Vitality Stadium', 'scheduled', NULL, NULL),
('Brighton & Hove Albion', 'Liverpool', 'Premier League', 'EPL', '14:30', '2026-03-21', 'American Express Stadium', 'scheduled', NULL, NULL),
('Fulham', 'Burnley', 'Premier League', 'EPL', '17:00', '2026-03-21', 'Craven Cottage', 'scheduled', NULL, NULL),
('Everton', 'Chelsea', 'Premier League', 'EPL', '15:00', '2026-03-21', 'Goodison Park', 'scheduled', NULL, NULL),
('Leeds United', 'Brentford', 'Premier League', 'EPL', '20:30', '2026-03-21', 'Elland Road', 'scheduled', NULL, NULL),
('Newcastle United', 'Sunderland', 'Premier League', 'EPL', '13:30', '2026-03-22', 'St James’ Park', 'scheduled', NULL, NULL),
('Aston Villa', 'West Ham United', 'Premier League', 'EPL', '15:45', '2026-03-22', 'Villa Park', 'scheduled', NULL, NULL),
('Arsenal', 'AFC Bournemouth', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Brentford', 'Everton', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Burnley', 'Brighton & Hove Albion', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Turf Moor', 'scheduled', NULL, NULL),
('Crystal Palace', 'Newcastle United', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Selhurst Park', 'scheduled', NULL, NULL),
('Chelsea', 'Manchester City', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Stamford Bridge', 'scheduled', NULL, NULL),
('Liverpool', 'Fulham', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Anfield', 'scheduled', NULL, NULL),
('Manchester United', 'Leeds United', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Old Trafford', 'scheduled', NULL, NULL),
('Nottingham Forest', 'Aston Villa', 'Premier League', 'EPL', '14:30', '2026-04-11', 'The City Ground', 'scheduled', NULL, NULL),
('Sunderland', 'Tottenham Hotspur', 'Premier League', 'EPL', '14:30', '2026-04-11', 'Stadium of Light', 'scheduled', NULL, NULL),
('West Ham United', 'Wolverhampton Wanderers', 'Premier League', 'EPL', '14:30', '2026-04-11', 'London Stadium', 'scheduled', NULL, NULL),
('A.F.C. Bournemouth', 'Manchester City', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Vitality Stadium', 'scheduled', NULL, NULL),
('Arsenal', 'Burnley', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Emirates Stadium', 'scheduled', NULL, NULL),
('Aston Villa', 'Liverpool', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Villa Park', 'scheduled', NULL, NULL),
('Brentford', 'Crystal Palace', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Gtech Community Stadium', 'scheduled', NULL, NULL),
('Chelsea', 'Tottenham Hotspur', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Stamford Bridge', 'scheduled', NULL, NULL),
('Everton', 'Sunderland', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Goodison Park', 'scheduled', NULL, NULL),
('Leeds United', 'Brighton & Hove Albion', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Elland Road', 'scheduled', NULL, NULL),
('Manchester United', 'Nottingham Forest', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Old Trafford', 'scheduled', NULL, NULL),
('Newcastle United', 'West Ham United', 'Premier League', 'EPL', '15:30', '2026-05-17', 'St James’ Park', 'scheduled', NULL, NULL),
('Wolverhampton Wanderers', 'Fulham', 'Premier League', 'EPL', '15:30', '2026-05-17', 'Molineux', 'scheduled', NULL, NULL),
('Brighton & Hove Albion', 'Manchester United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'American Express Stadium', 'scheduled', NULL, NULL),
('Burnley', 'Wolverhampton Wanderers', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Turf Moor', 'scheduled', NULL, NULL),
('Crystal Palace', 'Arsenal', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Selhurst Park', 'scheduled', NULL, NULL),
('Fulham', 'Newcastle United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Craven Cottage', 'scheduled', NULL, NULL),
('Liverpool', 'Brentford', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Anfield', 'scheduled', NULL, NULL),
('Manchester City', 'Aston Villa', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Etihad Stadium', 'scheduled', NULL, NULL),
('Nottingham Forest', 'A.F.C. Bournemouth', 'Premier League', 'EPL', '16:00', '2026-05-24', 'The City Ground', 'scheduled', NULL, NULL),
('Sunderland', 'Chelsea', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Stadium of Light', 'scheduled', NULL, NULL),
('Tottenham Hotspur', 'Everton', 'Premier League', 'EPL', '16:00', '2026-05-24', 'Tottenham Hotspur Stadium', 'scheduled', NULL, NULL),
('West Ham United', 'Leeds United', 'Premier League', 'EPL', '16:00', '2026-05-24', 'London Stadium', 'scheduled', NULL, NULL),
('Athletic Club','FC Barcelona','La Liga','LL','20:30','2026-03-08','San Mamés Stadium','scheduled',NULL,NULL),
('Atlético Madrid','Real Sociedad','La Liga','LL','20:30','2026-03-08','Wanda Metropolitano','scheduled',NULL,NULL),
('RC Celta','Real Madrid','La Liga','LL','20:30','2026-03-08','Abanca Balaídos','scheduled',NULL,NULL),
('RCD Espanyol','Real Oviedo','La Liga','LL','20:30','2026-03-08','RCDE Stadium','scheduled',NULL,NULL),
('Valencia CF','Deportivo Alavés','La Liga','LL','20:30','2026-03-08','Mestalla Stadium','scheduled',NULL,NULL),
('Getafe CF','Real Betis','La Liga','LL','20:30','2026-03-08','Coliseum Alfonso Pérez','scheduled',NULL,NULL),
('Villarreal CF','Elche CF','La Liga','LL','20:30','2026-03-08','Estadio de la Cerámica','scheduled',NULL,NULL),
('Levante UD','Girona FC','La Liga','LL','20:30','2026-03-08','Estadi Ciutat de València','scheduled',NULL,NULL),
('CA Osasuna','RCD Mallorca','La Liga','LL','20:30','2026-03-08','Estadio El Sadar','scheduled',NULL,NULL),
('Sevilla FC','Rayo Vallecano','La Liga','LL','20:30','2026-03-08','Ramón Sánchez Pizjuán','scheduled',NULL,NULL),

('Deportivo Alavés','Villarreal CF','La Liga','LL','20:30','2026-03-15','Mendizorrotza Stadium','scheduled',NULL,NULL),
('Atlético Madrid','Getafe CF','La Liga','LL','20:30','2026-03-15','Wanda Metropolitano','scheduled',NULL,NULL),
('FC Barcelona','Sevilla FC','La Liga','LL','20:30','2026-03-15','Spotify Camp Nou','scheduled',NULL,NULL),
('Real Betis','RC Celta','La Liga','LL','20:30','2026-03-15','Estadio Benito Villamarín','scheduled',NULL,NULL),
('Real Oviedo','Valencia CF','La Liga','LL','20:30','2026-03-15','Estadio Carlos Tartiere','scheduled',NULL,NULL),
('Girona FC','Athletic Club','La Liga','LL','20:30','2026-03-15','Estadi Montilivi','scheduled',NULL,NULL),
('Real Madrid','Elche CF','La Liga','LL','20:30','2026-03-15','Santiago Bernabéu','scheduled',NULL,NULL),
('RCD Mallorca','RCD Espanyol','La Liga','LL','20:30','2026-03-15','Visit Mallorca Stadium','scheduled',NULL,NULL),
('Rayo Vallecano','Levante UD','La Liga','LL','20:30','2026-03-15','Vallecas Stadium','scheduled',NULL,NULL),
('Real Sociedad','CA Osasuna','La Liga','LL','20:30','2026-03-15','Reale Arena','scheduled',NULL,NULL),

('Athletic Club','Real Betis','La Liga','LL','20:30','2026-03-22','San Mamés Stadium','scheduled',NULL,NULL),
('FC Barcelona','Rayo Vallecano','La Liga','LL','20:30','2026-03-22','Spotify Camp Nou','scheduled',NULL,NULL),
('Elche CF','RCD Mallorca','La Liga','LL','20:30','2026-03-22','Estadio Martínez Valero','scheduled',NULL,NULL),
('RCD Espanyol','Getafe CF','La Liga','LL','20:30','2026-03-22','RCDE Stadium','scheduled',NULL,NULL),
('Levante UD','Real Oviedo','La Liga','LL','20:30','2026-03-22','Estadi Ciutat de València','scheduled',NULL,NULL),
('Sevilla FC','Valencia CF','La Liga','LL','20:30','2026-03-22','Ramón Sánchez Pizjuán','scheduled',NULL,NULL),
('RC Celta','Deportivo Alavés','La Liga','LL','20:30','2026-03-22','Abanca Balaídos','scheduled',NULL,NULL),
('Real Madrid','Atlético Madrid','La Liga','LL','02:30','2026-03-23','Santiago Bernabéu','scheduled',NULL,NULL),
('CA Osasuna','Girona FC','La Liga','LL','20:30','2026-03-22','Estadio El Sadar','scheduled',NULL,NULL),
('Villarreal CF','Real Sociedad','La Liga','LL','20:30','2026-03-22','Estadio de la Cerámica','scheduled',NULL,NULL),

('Deportivo Alavés','CA Osasuna','La Liga','LL','22:30','2026-04-05','Mendizorrotza Stadium','scheduled',NULL,NULL),
('Atlético Madrid','FC Barcelona','La Liga','LL','22:30','2026-04-05','Wanda Metropolitano','scheduled',NULL,NULL),
('Real Betis','RCD Espanyol','La Liga','LL','22:30','2026-04-05','Estadio Benito Villamarín','scheduled',NULL,NULL),
('Girona FC','Villarreal CF','La Liga','LL','22:30','2026-04-05','Estadi Montilivi','scheduled',NULL,NULL),
('RCD Mallorca','Real Madrid','La Liga','LL','22:30','2026-04-05','Visit Mallorca Stadium','scheduled',NULL,NULL),
('Real Oviedo','Sevilla FC','La Liga','LL','22:30','2026-04-05','Estadio Carlos Tartiere','scheduled',NULL,NULL),
('Getafe CF','Athletic Club','La Liga','LL','22:30','2026-04-05','Coliseum Alfonso Pérez','scheduled',NULL,NULL),
('Valencia CF','RC Celta','La Liga','LL','22:30','2026-04-05','Mestalla Stadium','scheduled',NULL,NULL),
('Rayo Vallecano','Elche CF','La Liga','LL','22:30','2026-04-05','Vallecas Stadium','scheduled',NULL,NULL),
('Real Sociedad','Levante UD','La Liga','LL','22:30','2026-04-05','Reale Arena','scheduled',NULL,NULL),

('Athletic Club','Osasuna','La Liga','LL','22:30','2026-04-22','San Mamés Stadium','scheduled',NULL,NULL),
('Barcelona','Celta de Vigo','La Liga','LL','22:30','2026-04-22','Spotify Camp Nou','scheduled',NULL,NULL),
('Elche CF','Atlético Madrid','La Liga','LL','22:30','2026-04-22','Estadio Martínez Valero','scheduled',NULL,NULL),
('Girona FC','Real Betis','La Liga','LL','22:30','2026-04-22','Estadi Montilivi','scheduled',NULL,NULL),
('Levante UD','Sevilla FC','La Liga','LL','22:30','2026-04-22','Estadi Ciutat de València','scheduled',NULL,NULL),
('RCD Mallorca','Valencia CF','La Liga','LL','22:30','2026-04-22','Visit Mallorca Stadium','scheduled',NULL,NULL),
('Rayo Vallecano','RCD Espanyol','La Liga','LL','22:30','2026-04-22','Vallecas Stadium','scheduled',NULL,NULL),
('Real Madrid','Deportivo Alavés','La Liga','LL','22:30','2026-04-22','Santiago Bernabéu','scheduled',NULL,NULL),
('Real Oviedo','Villarreal CF','La Liga','LL','22:30','2026-04-22','Estadio Carlos Tartiere','scheduled',NULL,NULL),
('Real Sociedad','Getafe CF','La Liga','LL','22:30','2026-04-22','Reale Arena','scheduled',NULL,NULL),

('Alavés','Athletic Club','La Liga','LL','22:30','2026-05-03','Mendizorrotza Stadium','scheduled',NULL,NULL),
('Celta de Vigo','Elche CF','La Liga','LL','22:30','2026-05-03','Abanca Balaídos','scheduled',NULL,NULL),
('Espanyol','Real Madrid','La Liga','LL','22:30','2026-05-03','RCDE Stadium','scheduled',NULL,NULL),
('Getafe CF','Rayo Vallecano','La Liga','LL','22:30','2026-05-03','Coliseum Alfonso Pérez','scheduled',NULL,NULL),
('Girona FC','RCD Mallorca','La Liga','LL','22:30','2026-05-03','Estadi Montilivi','scheduled',NULL,NULL),
('Osasuna','FC Barcelona','La Liga','LL','22:30','2026-05-03','Estadio El Sadar','scheduled',NULL,NULL),
('Real Betis','Real Oviedo','La Liga','LL','22:30','2026-05-03','Estadio Benito Villamarín','scheduled',NULL,NULL),
('Sevilla FC','Real Sociedad','La Liga','LL','22:30','2026-05-03','Ramón Sánchez Pizjuán','scheduled',NULL,NULL),
('Valencia CF','Atlético Madrid','La Liga','LL','22:30','2026-05-03','Mestalla Stadium','scheduled',NULL,NULL),
('Villarreal CF','Levante UD','La Liga','LL','22:30','2026-05-03','Estadio de la Cerámica','scheduled',NULL,NULL),

('Athletic Club','Valencia CF','La Liga','LL','22:30','2026-05-10','San Mamés Stadium','scheduled',NULL,NULL),
('Atlético Madrid','RC Celta','La Liga','LL','22:30','2026-05-10','Wanda Metropolitano','scheduled',NULL,NULL),
('FC Barcelona','Real Madrid','La Liga','LL','22:30','2026-05-10','Spotify Camp Nou','scheduled',NULL,NULL),
('Elche CF','Deportivo Alavés','La Liga','LL','22:30','2026-05-10','Estadio Martínez Valero','scheduled',NULL,NULL),
('Levante UD','CA Osasuna','La Liga','LL','22:30','2026-05-10','Estadi Ciutat de València','scheduled',NULL,NULL),
('RCD Mallorca','Villarreal CF','La Liga','LL','22:30','2026-05-10','Visit Mallorca Stadium','scheduled',NULL,NULL),
('Rayo Vallecano','Girona FC','La Liga','LL','22:30','2026-05-10','Vallecas Stadium','scheduled',NULL,NULL),
('Real Oviedo','Getafe CF','La Liga','LL','22:30','2026-05-10','Estadio Carlos Tartiere','scheduled',NULL,NULL),
('Real Sociedad','Real Betis','La Liga','LL','22:30','2026-05-10','Reale Arena','scheduled',NULL,NULL),
('Sevilla FC','RCD Espanyol','La Liga','LL','22:30','2026-05-10','Ramón Sánchez Pizjuán','scheduled',NULL,NULL),

('Real Madrid','Athletic Club','La Liga','LL','22:30','2026-05-24','Santiago Bernabéu','scheduled',NULL,NULL),
('Valencia CF','FC Barcelona','La Liga','LL','22:30','2026-05-24','Mestalla Stadium','scheduled',NULL,NULL),
('Villarreal CF','Atlético Madrid','La Liga','LL','22:30','2026-05-24','Estadio de la Cerámica','scheduled',NULL,NULL),
('Espanyol','Sevilla FC','La Liga','LL','22:30','2026-05-24','RCDE Stadium','scheduled',NULL,NULL),
('CA Osasuna','Real Betis','La Liga','LL','22:30','2026-05-24','Estadio El Sadar','scheduled',NULL,NULL),
('Deportivo Alavés','Rayo Vallecano','La Liga','LL','22:30','2026-05-24','Mendizorrotza Stadium','scheduled',NULL,NULL),
('Getafe CF','Girona FC','La Liga','LL','22:30','2026-05-24','Coliseum Alfonso Pérez','scheduled',NULL,NULL),
('Real Oviedo','Valencia CF','La Liga','LL','22:30','2026-05-24','Estadio Carlos Tartiere','scheduled',NULL,NULL),
('RC Celta','Espanyol','La Liga','LL','22:30','2026-05-24','Abanca Balaídos','scheduled',NULL,NULL),
('RCD Mallorca','Sevilla FC','La Liga','LL','22:30','2026-05-24','Visit Mallorca Stadium','scheduled',NULL,NULL)
;
